apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - metadata-mysql-service.yaml
  - metadata-mysql-statefulset.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-deployment.yaml
  - worker-service.yaml

commonLabels:
  project: db-fleetops