apiVersion: v1
kind: Secret
metadata:
  name: db-fleetops-secret
  namespace: db-fleetops
type: Opaque
stringData:
  DB_FLEETOPS_DATASOURCE_PASSWORD: "dbfleetpw"

  METADATA_MYSQL_ROOT_PASSWORD: "rootpw"
  METADATA_MYSQL_DATABASE: "db_fleetops"
  METADATA_MYSQL_USERNAME: "dbfleet"
  METADATA_MYSQL_PASSWORD: "dbfleetpw"