services:
  target-mysql:
    image: mysql:8.4
    container_name: db-fleetops-target-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_TARGET_NAME}
      MYSQL_USER: ${DB_TARGET_USERNAME}
      MYSQL_PASSWORD: ${DB_TARGET_PASSWORD}

    ports:
      - "${DB_TARGET_PORT}:3306"

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD --silent"
        ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s

    volumes:
      - target-mysql-data:/var/lib/mysql

volumes:
  target-mysql-data: