apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: db-fleetops
  labels:
    app: grafana
    component: observability
spec:
  type: ClusterIP
  selector:
    app: grafana
    component: observability
  ports:
    - name: http
      port: 3000
      targetPort: http