apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: db-fleetops
  labels:
    app: prometheus
    component: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "db-fleetops-api"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets:
              - "db-fleetops-api:8080"
            labels:
              application: "db-fleetops"
              component: "api"
              environment: "minikube"

      - job_name: "db-fleetops-worker"
        metrics_path: "/actuator/prometheus"
        static_configs:
          - targets:
              - "db-fleetops-worker:8080"
            labels:
              application: "db-fleetops"
              component: "worker"
              environment: "minikube"